name: AzureAPI

on:
  push:
    branches: [ develop ]

env:
  resourceGroup: CBTAzure
  dnsLabel: cbtazuredns
  appName: cbtazureapi92

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az appservice plan create -g ${{ env.resourceGroup }} -n azureapiplan --is-linux

    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az webapp create -g ${{ env.resourceGroup }} -p azureapiplan -n ${{ env.appName }} --runtime "python|3.6"

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.appName }}
        #package: .
        #startup-command: python app.py
